include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/presentation/views/main_menu/settings_view/licenses/oss_licenses.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    lines_longer_than_80_chars: false
    constant_identifier_names: false